---
title: "horizontalImplement"
output: html_document
runtime: shiny
---

## Hi this is a gallery test

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(htmltools)
library(glue)
library(Slick)
library(magick)
library(shiny)
# Main gallery function
my_gallery <- function(images, height = "250px" ){
  # images are character vectors of URLs or local file path
  img_tags <- lapply(images, function(src){
    tags$img(src = src, style = glue("height:{height}; margin-right:10px; border-radius;8px;"))
  })
  
  tags$div(
    style = "display:flex; overflow-x:auto; white-space:nowrap; padding:10px;",
    img_tags
  )
}

```

look at my cats!

```{r echo=FALSE, message=FALSE, warning=FALSE}
my_gallery(c("https://th.bing.com/th/id/R.f8b72b32b467a4c9df022202360b79de?rik=DfgRIyPIhVcz2Q&pid=ImgRaw&r=0", "https://tse2.mm.bing.net/th/id/OIP.kqNv2fqs2keQhU_Nn7SwNwHaFS?r=0&rs=1&pid=ImgDetMain&o=7&rm=3", "https://tse4.mm.bing.net/th/id/OIP.rXUtZZioKcMB2Z9PH4JawgHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3", "https://i.pinimg.com/originals/4a/a6/f1/4aa6f134f5f327fcc01a1ced9f5c07e9.jpg"))
```

